Repository RPalaciosDev/Project2_CST438-01_2252, pull requests merged in 2025-03, with the labels that each got.

#22 Setup AWS S3 and MongoDB
  compose.yaml
  image-storage-service/Dockerfile
  image-storage-service/README.md
  image-storage-service/build.gradle
  image-storage-service/gradle/wrapper/gradle-wrapper.properties
  image-storage-service/gradlew
  image-storage-service/src/main/java/com/cst438/image/ImageStorageServiceApplication.java
  image-storage-service/src/main/java/com/cst438/image/config/S3Config.java
  image-storage-service/src/main/java/com/cst438/image/config/SecurityConfig.java
  image-storage-service/src/main/java/com/cst438/image/controller/ImageMetadataController.java
  image-storage-service/src/main/java/com/cst438/image/model/ImageMetadata.java
  image-storage-service/src/main/java/com/cst438/image/model/ImageMetadataDocument.java
  image-storage-service/src/main/java/com/cst438/image/repository/ImageMetadataRepository.java
  image-storage-service/src/main/java/com/cst438/image/service/ImageMetadataService.java
  image-storage-service/src/main/java/com/cst438/image/service/StorageService.java
  image-storage-service/src/main/resources/application.properties
  mongo-init.js
Labels: enhancement

#27 starting to see some progress now
  frontend/0Auth2RedirectHandler.jsx
  frontend/app/(app)/_layout.tsx
  frontend/app/(app)/index.tsx
  frontend/app/(auth)/ProtectedRoute.jsx
  frontend/app/(auth)/_layout.tsx
  frontend/app/App.js
  frontend/app/_layout.tsx
  frontend/app/home.tsx
  frontend/app/index.tsx
  frontend/app/services/auth-service.js
  frontend/app/sign-in.tsx
  frontend/app/sign-up.tsx
  frontend/components/TierList.tsx
  frontend/config/.eslintrc.js
  frontend/config/.prettierrc.js
  frontend/config/jest.config.js
  frontend/config/tsconfig.base.json
  frontend/package.json
  frontend/services/auth.ts
  frontend/sign-in.tsx
  frontend/tsconfig.json
Labels: bug

#29 Fix/28 image storage reconfig
  .env.example
  .gitignore
  README.md
  compose.yaml
  docker-compose.prod.yml
  image-storage-service/Dockerfile
  image-storage-service/README.md
  image-storage-service/build.gradle
  image-storage-service/src/main/java/com/cst438/image/ImageStorageServiceApplication.java
  image-storage-service/src/main/java/com/cst438/image/config/MongoConfig.java
  image-storage-service/src/main/java/com/cst438/image/service/StorageService.java
  image-storage-service/src/main/resources/application.properties
  mongo-init.js
  secrets/db_password.txt
  setup.sh
Labels: fix

#38 Configured image-storage for railway deployment
  .railway.toml
  NGINX_REMOVAL.md
  RAILWAY_DEPLOYMENT.md
  README.md
  auth-user-service/src/main/java/group_3/tier_api/backend/config/SecurityConfig.java
  auth-user-service/src/main/java/group_3/tier_api/backend/security/OAuth2AuthenticationSuccessHandler.java
  chat_api/src/main/java/com/group3/chat_api/config/WebConfig.java
  chat_api/src/main/java/com/group3/chat_api/config/WebSocketConfig.java
  compose.yaml
  docker-compose.prod.yml
  frontend/Dockerfile
  frontend/services/api.js
  frontend/services/auth.ts
  image-storage-service/.env.example
  image-storage-service/Dockerfile
  image-storage-service/IMPLEMENTATION_DETAILS.md
  image-storage-service/RAILWAY.md
  image-storage-service/README.md
  image-storage-service/railway.json
  image-storage-service/src/main/java/com/cst438/image/config/SecurityConfig.java
  image-storage-service/src/main/java/com/cst438/image/controller/ServiceInfoController.java
  image-storage-service/src/main/resources/application.properties
  mongo-init.js
  nginx/conf.d/api.conf
  nginx/nginx.conf
  nginx/nginx.prod.conf
  nginx/ssl/fullchain.pem
  nginx/ssl/privkey.pem
  tier-list-service/src/main/java/group_3/tierlistservice/config/MongoDBConfig.java
  tier-list-service/src/main/java/group_3/tierlistservice/config/WebConfig.java
Labels: enhancement, database

#41 Corrects CORS origins for websockets
  chat_api/src/main/java/com/group3/chat_api/config/WebSocketConfig.java
Labels: bug, fix

#40 Fix/test auth pass jwt
  auth-user-service/Dockerfile
  auth-user-service/RAILWAY_DEPLOYMENT.md
  auth-user-service/railway.json
  auth-user-service/src/main/java/group_3/tier_api/backend/config/SecurityConfig.java
  auth-user-service/src/main/java/group_3/tier_api/backend/controller/HealthController.java
  auth-user-service/src/main/java/group_3/tier_api/backend/models/AuthProvider.java
  auth-user-service/src/main/java/group_3/tier_api/backend/security/JwtUtils.java
  auth-user-service/src/main/java/group_3/tier_api/backend/security/OAuth2AuthenticationSuccessHandler.java
  auth-user-service/src/main/resources/application.yml
  frontend/Dockerfile
  frontend/Select
  frontend/package.json
  frontend/railway.json
  frontend/services/api.js
  image-storage-service/Dockerfile
  regenerate-wrapper.bat
Labels: fix, frontend

#42 matching setup
  ml-service/README.MD
  ml-service/app.py
  ml-service/model/setupexample.py
  ml-service/requirements.txt
Labels: enhancement

#55 RabbitMQ Config
  chat_api/src/main/java/com/group3/chat_api/config/RabbitMQConfig.java
  chat_api/src/main/java/com/group3/chat_api/controller/ChatController.java
  chat_api/src/main/java/com/group3/chat_api/controller/ConversationController.java
  chat_api/src/main/java/com/group3/chat_api/dto/ConversationRequest.java
  chat_api/src/main/java/com/group3/chat_api/dto/ConversationResponse.java
  chat_api/src/main/java/com/group3/chat_api/handler/RabbitMQConsumer.java
  chat_api/src/main/java/com/group3/chat_api/mapper/ChatMapper.java
  chat_api/src/main/java/com/group3/chat_api/mapper/ConversationMapper.java
  chat_api/src/main/java/com/group3/chat_api/model/Chat.java
  chat_api/src/main/java/com/group3/chat_api/model/Conversation.java
  chat_api/src/main/java/com/group3/chat_api/repository/ConversationRepository.java
  chat_api/src/main/java/com/group3/chat_api/service/ConversationService.java
Labels: enhancement

#56 Configure RabbitMQ for Services + Match Queue Implementation
  auth_user_api/build.gradle
  auth_user_api/src/main/java/group_3/auth_user_api/config/RabbitMQConfig.java
  image-storage-service/build.gradle
  image-storage-service/src/main/java/com/cst438/image/config/RabbitMQConfig.java
  ml-service/README.MD
  ml-service/app.py
  ml-service/rabbitmq.py
  ml-service/requirements.txt
Labels: documentation, enhancement

#62 WS Topic Channels
  chat_api/Dockerfile
  chat_api/railway.json
  chat_api/railway.toml
  chat_api/src/main/java/com/group3/chat_api/config/RabbitMQConfig.java
  chat_api/src/main/java/com/group3/chat_api/config/WebConfig.java
  chat_api/src/main/java/com/group3/chat_api/config/WebSocketConfig.java
  chat_api/src/main/java/com/group3/chat_api/controller/ChatController.java
  chat_api/src/main/java/com/group3/chat_api/controller/ConversationController.java
  chat_api/src/main/java/com/group3/chat_api/controller/RootController.java
  chat_api/src/main/java/com/group3/chat_api/controller/WSChatController.java
  chat_api/src/main/java/com/group3/chat_api/dto/ConversationManagerResponse.java
  chat_api/src/main/java/com/group3/chat_api/dto/ConversationResponse.java
  chat_api/src/main/java/com/group3/chat_api/handler/RabbitMQConsumer.java
  chat_api/src/main/java/com/group3/chat_api/handler/RabbitMQProducer.java
  chat_api/src/main/java/com/group3/chat_api/handler/WebSocketEventListener.java
  chat_api/src/main/java/com/group3/chat_api/handler/WebSocketHandler.java
  chat_api/src/main/java/com/group3/chat_api/mapper/ConversationManagerMapper.java
  chat_api/src/main/java/com/group3/chat_api/mapper/ConversationMapper.java
  chat_api/src/main/java/com/group3/chat_api/model/Chat.java
  chat_api/src/main/java/com/group3/chat_api/model/ChatMessage.java
  chat_api/src/main/java/com/group3/chat_api/model/Conversation.java
  chat_api/src/main/java/com/group3/chat_api/model/ConversationManager.java
  chat_api/src/main/java/com/group3/chat_api/model/MessageType.java
  chat_api/src/main/java/com/group3/chat_api/repository/ChatRepository.java
  chat_api/src/main/java/com/group3/chat_api/repository/ConversationManagerRepository.java
  chat_api/src/main/java/com/group3/chat_api/repository/ConversationRepository.java
  chat_api/src/main/java/com/group3/chat_api/service/ChatService.java
  chat_api/src/main/java/com/group3/chat_api/service/ConversationManagerService.java
  chat_api/src/main/java/com/group3/chat_api/service/ConversationService.java
Labels: bug, documentation, enhancement

#69 Feature/68 final tier list service deployment
  PR_DESCRIPTION.md
  frontend/app/tierlists/index.tsx
  image-storage-service/src/main/java/com/cst438/image/controller/ImageMetadataController.java
  image-storage-service/src/main/java/com/cst438/image/repository/ImageMetadataRepository.java
  image-storage-service/src/main/java/com/cst438/image/service/ImageMetadataService.java
  ml-service/app.py
  ml-service/requirements.txt
  tier-list-service/src/main/java/group_3/tierlistservice/config/WebClientConfig.java
  tier-list-service/src/main/java/group_3/tierlistservice/controller/TierlistTemplateController.java
  tier-list-service/src/main/java/group_3/tierlistservice/service/ImageServiceClient.java
  tier-list-service/src/main/java/group_3/tierlistservice/service/TierlistTemplateService.java
  tier-list-service/src/main/resources/application.yml
Labels: enhancement

#82 Chat Handlers and Final UI
  chat_api/build.gradle
  chat_api/src/main/java/com/group3/chat_api/config/WebConfig.java
  chat_api/src/main/java/com/group3/chat_api/config/WebSocketConfig.java
  chat_api/src/main/java/com/group3/chat_api/controller/ChatController.java
  chat_api/src/main/java/com/group3/chat_api/controller/ConversationController.java
  chat_api/src/main/java/com/group3/chat_api/controller/WSChatController.java
  chat_api/src/main/java/com/group3/chat_api/dto/ChatResponse.java
  chat_api/src/main/java/com/group3/chat_api/handler/RabbitMQConsumer.java
  chat_api/src/main/java/com/group3/chat_api/mapper/ChatMapper.java
  chat_api/src/main/java/com/group3/chat_api/model/Chat.java
  chat_api/src/main/java/com/group3/chat_api/model/ChatMessage.java
  chat_api/src/main/java/com/group3/chat_api/model/ConversationManager.java
  chat_api/src/main/java/com/group3/chat_api/repository/ConversationManagerRepository.java
  chat_api/src/main/java/com/group3/chat_api/service/ChatService.java
  chat_api/src/main/java/com/group3/chat_api/service/ConversationManagerService.java
  chat_api/src/main/java/com/group3/chat_api/service/ConversationService.java
  frontend/Dockerfile
  frontend/app/_layout.tsx
  frontend/app/auth-check.tsx
  frontend/app/browse.tsx
  frontend/app/chats/ChatScreen.tsx
  frontend/app/chats/[chatId].tsx
  frontend/app/chats/_layout.tsx
  frontend/app/chats/index.tsx
  frontend/app/startup.tsx
  frontend/app/tier-builder.tsx
  frontend/hooks/useConversation.tsx
  frontend/package.json
  frontend/services/api.js
  frontend/services/auth.ts
  frontend/store/auth-store.ts
  ml-service/app.py
  ml-service/rabbitmq.py
Labels: enhancement, database, fix, frontend
